### PR TITLE
Rss

### PR DESCRIPTION
**Pull request by dl-nice**
https://github.com/nemfoundation/nem2-desktop-wallet/issues/713

### CODE REVIEW

**Comment by decentraliser** [comment]
not sure about the timestamp and the font
image

**Comment by decentraliser** [comment]
Are you sure that RSSParser().parseString will sanitize the payload?
I had a quick check and saw nothing about that...

note that using `<pre>` does not make html injection safe

**Comment by dl-nice** [comment]
The pre element defines pre-formatted text. Text enclosed in pre elements usually retains spaces and newlines. And the text will be rendered in a monospaced font

**Comment by decentraliser** [comment]
the pre element does not protect from XSS attacts

**Comment by dl-nice** [comment]
how about iframe

**Comment by dl-nice** [comment]
hold .I will be use iframe ,now fix ui

**Pull request closed without merging**
