### PR TITLE
rebase harvesting

### PR DESCRIPTION
**Pull request by domakun**

### CODE REVIEW

**Comment by evias** [comment]
please fix conflict (probably due to rebase conflict)

**Comment by domakun** [comment]
> please fix conflict (probably due to rebase conflict)

fixed

**Comment by decentraliser** [comment]
so, still against the "local node configuration", but I guess it should not be a blocker for merge

**Comment by decentraliser** [comment]
I think there should be a confirmation screen where clicking on "unlink" to let the user confirm

**Comment by decentraliser** [comment]
image
I don't think that's a wanted behaviour (false, true, true)

**Comment by domakun** [comment]
> why is there changes in `TransactionConfirmation` component? Also don't think the TransactionList should be affected by the harvesting UI changes, if so then in a different PR based on this one.

I rebase from nemfoundation/master, and I saw UI bug in TransactionConfirmation component after I update harvesting, so I update this file. So as transaction list and other files. I didn't update logic code but onli stylesheet.

**Comment by decentraliser** [comment]
The choice of harvesting node has to be updated (filter nodes by network types)
If the function is the same as MenuBar get nodeList, extract it and use the same

**Comment by decentraliser** [comment]
false, true, false should not happen
image

**Comment by evias** [comment]
notes made on slack:

- "Link or change” should be `Remote account link`
- “Node network” should be `Harvesting node`
- “Delegated request” should be `Harvesting request`
- “Requesting” should be `Harvesting delegation request`
- "Request transaction has been confirmed" should be `Status of harvesting delegation request`
- Remove second status row
- "Remote node" should be `Node host`
- "Remote node's public key" should be `Node public key`

**Comment by decentraliser** [comment]
image
refresh icon should not be there

**Comment by decentraliser** [comment]
1, 2 and 3 should never appear altogether (it was Ok in my PR this morning)

**Comment by decentraliser** [comment]
this error should not occur (and it will get even more womplex with nodeList PR)
image

**Comment by decentraliser** [comment]
The generation of child account should be optimized the same wayt @dl-nice did today with the getTenAddressesFromMnemonic function

https://github.com/nemfoundation/nem2-desktop-wallet/pull/821/files#diff-6aef283bea9f901a3dceecee177e1712R73-R76

**Comment by decentraliser** [comment]
In delegated check password dialog, show property in the Vue file is not defined

**Comment by decentraliser** [comment]
We should validate this PR on top of the node list PR

**Pull request merged**
