### PR TITLE
multisig review

### LINKED ISSUE #543: Multisig Improvements
- [ ] Support multiple levels (currently, only one multisig level is handled
- [ ] The multisig tree collapses any time the utilising data is refreshed

image

### LINKED ISSUE #851: Co-sign transaction does not reach bottom-level signer in multilevel multisig
multisig001

I set up this multilevel multisig configuration.
A sent a transaction to transfer mozaic from Red to B, but none of the bottom 9 signers have received the Co-sign transaction.

### LINKED ISSUE #852: Mosaic / Namespace creation broken for multisig accounts that have more than 1 cosigner
To create a mosaic for a multisig account, the co-signer selected the multisig account and pressed the create button, but nothing happened.

### LINKED ISSUE #862: Active Account address should not show in multisig modification "From" dropdown

### PR DESCRIPTION
**Pull request by decentraliser**
PR based on:
 #850 - Decouple balances from AppWallet
 #855 - Mosaic fixes

Multi-level multisig support:
* Show all child accounts in the multisig sender dropdown fixes #543
* Get partial transactions of all child accounts #543, fixes #851

Bugfixes
* Fix mosaic and namespace transactions (broken for multisig with more than one cosigner) fixes #852
* Fix some unit tests that were making network calls #859
* Add config option in SignerSelector to hide active account address, fixes #862 

Performance improvement
* Implement a sequential fetching method to get children accounts partial transactions
* All multisig info come from the parent account GraphInfo (increases speed, decreases the number of network calls)

Code improvement 
* Remove duplicate code from multisig forms by using store getters #771

UI
* Add transactions to cosign in the transaction list
* Multisig Tree: All children multisig info is directly available #543

### CODE REVIEW

**Comment by domakun** [comment]
I can get partail transaction from node, but the partail transaction didn't show in transation list or cosig-page.
image

**Comment by decentraliser** [comment]
@domakun is the TCGJN account supposed to cosign this partial transaction?
or is it a _recipient_ of the partial transaction?

**Comment by domakun** [comment]
3-co:	C3F4D0419276694284A03C5B2EE83101F937095C6D39AD9A57B1F7B33A2272D5
	0AD20F3CE2D13A16D22C2EE92688F556BB494F850FE821FF3A72D07446B5F5DC
	TCJGNHQ66UZV7U7WDPVQVJ6Z7WCLKU57647BJYEF

4-co:	B252CBBAD950E2C7E4FB577AE9A2AE30439CE8BC7FD1F55EAC9502DD6964F4A7
	EEC8A10E625804FD060DB7673D48C8B3BB014F19A42E82F10F058D4E612F76DC
	TADIVXWIX3UWOHYF6FL5GNKKGR4LUH6IHZZBLREA

3-co (TCGJN) is the receiver with 50 xem, 4-co is the sender with 29xem

**Comment by decentraliser** [comment]
TCJN should not be able to see the transaction if it is not cosigned by the others, so it sounds like it is the expected behaviour

**Pull request closed without merging**
